language: go
dist: trusty

env:
  - CODECOV_TOKEN="4d6a6bcf-f6cd-4abb-9c62-8bb2028d01e2"

go:
 - 1.12.5

# 分支白名单
branches:
  only:
    - master
    - develop

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - go get -v ./...

script:
  - go test -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
